# RabbitMQ

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GCP_PROJECT_ID
    value: "gcp-automated-blog-prod"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: INSTANCE_NAME
    value: "autoblog-prod-bastion-host"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: REMOTE_HOST
    value: "b-891751b1-7ad5-48f6-9436-91f995fa1761.mq.eu-west-1.on.aws"
